package weloveclouds.ecs.core;

/**
 * Created by Benoit on 2016-11-22.
 */
public enum EcsStatus {
    WAITING_FOR_LOAD_BALANCER_INITIALIZATION, INITIALIZING_SERVICE, UPDATING_METADATA, INITIALIZED, STARTING_LOAD_BALANCER,
    STARTING_NODE, STOPPING_NODE, REMOVING_NODE, ADDING_NODE, SHUTTING_DOWN_NODE,
    WAITING_FOR_SERVICE_INITIALIZATION, INITIALIZING_LOAD_BALANCER
}
