package weloveclouds.ecs.core;

/**
 * Created by Benoit on 2016-11-22.
 */
public enum EcsStatus {
    UNINITIALIZED, INITIALIZING_SERVICE, UPDATING_METADATA, INITIALIZED, STARTING_LOAD_BALANCER,
    STARTING_NODE, STOPPING_NODE, REMOVING_NODE, ADDING_NODE, SHUTDOWNING_NODE,
    ARCHITECTURE_READY_FOR_INITIALIZATION
}
